source: src

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: _posts
    values:
      layout: "post"
      permalink: /blog/:year/:title:output_ext
  -
    scope:
      path: _drafts
    values:
      layout: "post"
      permalink: /blog/:year/:title:output_ext

kramdown: 
  input: GFM
  syntax_highlighter: rouge

# sass: 
#   style: compressed

# svg:
#   optimize: true

icon_list:
  default_path: /images/logos/
  defaults:
    ul: class="tech-list"
    svg: overflow="visible" class="icon" width="24"

picture:
  source: images/source_files
  output: images/generated

css:
  accent-color: '#743037'
  accent-hover-color: '#220043'
  background-color: '#FAFAFA'
  foreground-color: '#464646'
  light-text-color: '#636363'
