plugins:
  - jekyll-inline-svg 

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: _posts
    values:
      layout: "post"
      permalink: /blog/:year/:title:output_ext

svg:
  optimize: true
